### ISSUE TITLE
Buzzer Support

### ISSUE THREAD

**Issue by firepower9966** [pellcorp/creality#112]
Add support for Buzzer as used in Creality Helper Script.
https://guilouz.github.io/Creality-Helper-Script-Wiki/helper-script/buzzer-support/

**Comment by pellcorp** [comment]
https://github.com/Guilouz/Creality-Helper-Script/tree/main/files/buzzer-support

**Comment by firepower9966** [comment]
Thank You

**Comment by pellcorp** [comment]
Ah sorry I closed it by accident, seems like it would be pretty easy to do

**Comment by firepower9966** [comment]
i updated, and restarted, and beep cmd not recognised. no macro beep.
