### ISSUE TITLE
Fan Controls

### ISSUE THREAD

**Issue by TrainAss** [pellcorp/creality#128]
This is something that is rare, but can happen. If the SoC fan fails, and it needs to be replaced with a PWM fan, the easiest way to do that is to use an open CNC header on the motherboard. Fan config can be updated as follows

```
[temperature_fan soc_fan]
pin: PA0
cycle_time: 0.0100
kick_start_time: 0.5
hardware_pwm: false
max_power: 1
shutdown_speed: 0
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100
control: watermark
max_delta: 2
target_temp: 35.0
max_speed: 1.0
min_speed: 0.0
#tachometer_pin:PC6
```

This basically replaces the stock fan pin with a CNC header fan. Fan only comes on when the SoC reaches 35C, otherwise it's off.

[fans_control.txt](https://github.com/user-attachments/files/16739212/fans_control.txt)

**Comment by pellcorp** [comment]
So config overrides supports adding new sections but not removing now, I think it should just satisfy your requirements.
