### ISSUE TITLE
Add filament sensor control into start and end print macro

### ISSUE THREAD

**Issue by TrainAss** [pellcorp/creality#158]
Add the following in to the start print macro to ensure the filament sensor is enabled before a print starts.

`SET_FILAMENT_SENSOR SENSOR=filament_sensor ENABLE=1`

--

Add the following to the end print macro to shut it off between prints

`SET_FILAMENT_SENSOR SENSOR=filament_sensor ENABLE=0`

**Comment by pellcorp** [comment]
I am happy to make the change, but I don't understand why its necessary, I thought the filament sensor was enabled all the time, what is bad about that?

**Comment by pellcorp** [comment]
I will add this but make it configurable in case someone needs to turn this off

**Comment by pellcorp** [comment]
it still won't disable it for CANCEL_PRINT though

**Comment by pellcorp** [comment]
OK i have merged this, but it won't disable filament sensor in cancel print, not sure how best to do that.

**Comment by TrainAss** [comment]
In the cancel print macro add 

SET_FILAMENT_SENSOR SENSOR=filament_sensor ENABLE=0

Which will disable it.

As for why this is necessary, having it on all the time can cause a false runout trigger if you're doing any sort of testing or calibrations or any situation where you're bypassing the sensor.
