### ISSUE TITLE
Mainline klipper?

### ISSUE THREAD

**Issue by MrmysteryV** [pellcorp/creality#160]
Does this mod automatically change creality's old version of klipper to mainline? 
Thanks

**Comment by pellcorp** [comment]
It is kind of mainline. it is my fork of klipper which is rebased onto mainline every few months, last rebase was late august.

But there are some features specific to K1 that are not in mainline, so its mainline+ some creality specific stuff, like support for their GD32 chips which I do not think will ever be merged to mainline.

Plus my klipper fork has the creality specific firmware bits and pieces as well.

**Comment by MrmysteryV** [comment]
> It is kind of mainline. it is my fork of klipper which is rebased onto mainline every few months, last rebase was late august.
> 
> But there are some features specific to K1 that are not in mainline, so its mainline+ some creality specific stuff, like support for their GD32 chips which I do not think will ever be merged to mainline.
> 
> Plus my klipper fork has the creality specific firmware bits and pieces as well.

Thanks for the reply. Does that mean I can install klipperscreen and things like happy hare, as well as being able to do a larger than 6x6 mesh?
