### ISSUE TITLE
Print Area not centered

### ISSUE THREAD

**Issue by Shawng84** [pellcorp/creality#172]
This is my first time messing with the cnfg files in klipper. I have a K1 with Zero mount for Eddy. After getting everything setup and calibrated when I print something, EX-first layer test, its not centered in the bed. To me it needs to -5 on the X and -5 on the Y. I messed with the bed mesh and the min & max in the printer config but nothing works. what am I missing? is it in the slicer?

**Comment by pellcorp** [comment]
Best to ask a  question like this on the discord, I am not sure, but others maybe able to help you.
https://github.com/pellcorp/creality/wiki/Simple-AF-BTT-Eddy#where-can-i-get-help
