### ISSUE TITLE
Simple AF upgrades

### ISSUE THREAD

**Issue by pollinolas** [pellcorp/creality#183]
Hello, how can I know if there is a simple AF update available?

**Comment by pellcorp** [comment]
I am working on something that would give you basic idea by running a macro:
https://github.com/pellcorp/creality/pull/185

Needs some testing, but should be able to merge it this week some time, I will let you know when its been merged.

**Comment by pellcorp** [comment]
this has now been merged, you can update like this:

```
/usr/data/pellcorp/k1/installer.sh --update-repo
/usr/data/pellcorp/k1/installer.sh --update
```

And then the `CHECK_UPDATES` macro can be used to query for updates.
