### ISSUE TITLE
Creality Print Service?

### ISSUE THREAD

**Issue by MehItsOk** [pellcorp/creality#193]
Dumb question, i didnt want to bother asking but i cant figure it out on my own. what service would i need to add back in to let "Creality Print" see the printer? I do daily Orca i just wanted to see if it was at all possible.

**Comment by pellcorp** [comment]
Sorry but just not possible.  Creality print is exposed by a service which we cannot run on Simple AF as its not standalone, it requires on a bunch of different services.  I don't know whether creality print can also be used just like orca slicer configures a printer.
