### ISSUE TITLE
incorrect screws tilt adjust coordinates for k1 max

### ISSUE THREAD

**Issue by dprossner** [pellcorp/creality#202]
I have corrected the coordinates for screws tilt adjust in btteddy-k1m.cfg to properly center the eddy probe over the bed leveling screw points. 

These are for the default probe mount and have been tested to work perfectly:

screw1: 42,23
screw1_name: front left
screw2: 301,23
screw2_name: front right
screw3: 271,272
screw3_name: rear right
screw4: 71,272
screw4_name: rear left

These are for the rear probe mount. They have been calculated from given probe offsets on printables applied to the measured screw locations from Guilouz, yet are untested:

screw1: 19,-1.82
screw1_name: front left
screw2: 278,-1.82
screw2_name: front right
screw3: 248,247.18
screw3_name: rear right
screw4: 48,247.18
screw4_name: rear left

**Comment by pellcorp** [comment]
Ah brilliant, I will amend the config
