### ISSUE TITLE
BTT Eddy Temperature Calibration

### ISSUE THREAD

**Issue by roofuskit** [pellcorp/creality#203]
Does this version of klipper support the temperature calibration required to reliably use the Eddy as a homing end-stop?

**Comment by pellcorp** [comment]
yes

https://github.com/pellcorp/creality/wiki/Simple-AF-BTT-Eddy#temperature-compensation-calibration

**Comment by pellcorp** [comment]
For these types of questions you will get a faster answer via discord:
https://github.com/pellcorp/creality/wiki/Simple-AF-BTT-Eddy#where-can-i-get-help
