### ISSUE TITLE
Add Knomi support

### ISSUE THREAD

**Issue by Ledzpg** [pellcorp/creality#220]
Hi.
I've installed the Knomi V2 on my K1 Max, running Simple AF with a BTT Microprobe, and the knomi macros from BTT overrides the Simple AF macros, adding the btt knomi commands for status before and after, but causes errors.

Knomi macros from btt git: https://github.com/bigtreetech/KNOMI/blob/master/KNOMI.cfg

The M109 and M190 macros work well, but the G28 and the BED_MESH_CALIBRATE macros doesn't.

The solution found (and tested) was to comment the G28 and BED_MESH_CALIBRATE macros on knomi.cfg and add the knomi commands directly in the sensorless.cfg and start_end.cfg files, as attached.
[sensorless.txt](https://github.com/user-attachments/files/17689569/sensorless.txt)
[start_end.txt](https://github.com/user-attachments/files/17689570/start_end.txt)

**Comment by pellcorp** [comment]
Ok this has been done

https://github.com/pellcorp/creality/wiki/Simple-AF-Custom-Macro-Hooks#knomi-support
