### ISSUE TITLE
Add aux fan variable to end print 

### ISSUE THREAD

**Issue by verrilltp** [pellcorp/creality#277]
Adding in a aux fan variable in start_end.cfg for the end_print macro. 
Off by default, and having either a variable temp wait for nozzle or time till shut off that the user can set in client_variable.

**Comment by pellcorp** [comment]
Trying to think about how to best implement this.   Can you post your end print that you are currently using so I can kind of visualise what this might look like?

**Comment by pellcorp** [comment]
I am kind of thinking it makes more sense to have aux fan on until nozzle is at temp where the nozzle MCU fan goes off, which by default is 40c.   And perhaps both the part fan and aux fan should be on.
