### ISSUE TITLE
"On a K1M, you can use the lidar cable either directly by repinning it or via the pass through lidar port on the toolhead" 

### ISSUE THREAD

**Issue by Roadkyll** [pellcorp/creality#286]
Hello,

I have ordered the Cartographer3D Probe, and now I am double-checking myself.

Reading the information on Simple AF, it says, "On a K1M, you can use the lidar cable either directly by repinning it or via the pass-through lidar port on the tool head." Is this correct? If I can plug it into the tool head, installing new cables around it would save time.

Also, do I need to reinstall Klipper since the printer is already rooted?

Sorry for the stupid questions.

Glenn

**Comment by pellcorp** [comment]
You must follow the installation guide for Simple AF
You must do a factory reset - use the method in the guide NOT the Helper Script or any other method
And then follow the rest of the guide.
Yes if you have a K1M you should be able to connect it to the toolhead

But please join the Simple-AF discord to get more help, opening an issue is really only for bugs and feature requests.
