### ISSUE TITLE
Make start config pull chamber temp from slicer

### ISSUE THREAD

**Issue by clutchkick512** [pellcorp/creality#309]
When printing ABS ASA etc I often forget to override the chamber temp to above 35c. Can we modify the start code to have it pull that info from slicer and apply it at the start before homing.

**Comment by pellcorp** [comment]
So for now there is a workaround which is to add the M141 before START_PRINT, I think for now we will just let that be
https://discord.com/channels/999445685298536638/1312686051378200576
