### ISSUE TITLE
Calibrate_Cartographer Macro/Calibrate_Scan Macro

### ISSUE THREAD

**Issue by DubiousBiscuit** [pellcorp/creality#324]
These two Macros should be renamed to something more relatable. Also, probably need to change the instructions to match the final iteration of the macro name...I think Calibrate Touch...As this stands Probe Calibrate isn't referenced anywhere else..This may also need to apply to the scan macro - I have not tried it as I use the touch option for my cart. 
![image](https://github.com/user-attachments/assets/9cef34e8-0581-4831-857b-b8379509aac0)

**Comment by DubiousBiscuit** [comment]
I'm not sure but I think the last step from the original wiki isn't working. Calibrate=1
I'm going to walk through it again.

**Comment by ZeroDotCMD** [comment]
I haven't used the Wiki version of calibration since I did the macro. So I wouldn't know. this would be a question for pellcorp.

**Comment by DubiousBiscuit** [comment]
I'm sorry it's 3:23 AM here, I misspoke. I meant that step is missing from your macro or at the very least doesn't appear to be working. CARTOGRAPHER_TOUCH CALIBRATE=1. Looking at your macro it's there but it didn't execute when I was documenting the steps of your macro.

**Comment by ZeroDotCMD** [comment]
I've just ran through and tested the calibration macro. `STEP 5 - CALIBRATE TOUCH` is working on my end.

**Comment by DubiousBiscuit** [comment]
I'll re-run it on mine. I had to a clean install so maybe it will work for me now. Thank you.

**Comment by DubiousBiscuit** [comment]
it did work on mine after the clean install. I'm closing this now.
