### ISSUE TITLE
Clarification FAQ Stepper min max

### ISSUE THREAD

**Issue by DubiousBiscuit** [pellcorp/creality#325]
Reading the FAQ on how to adjust my probe for different configurations.

Stepper_y and Stepper_x min max are referred to this way:
![Screenshot 2024-12-04 191756](https://github.com/user-attachments/assets/359e3e8a-efa0-419b-a325-19f77e0759d9)
Just want to clarify that we're referring to this section as the nomenclature is different:
![Screenshot 2024-12-04 191556](https://github.com/user-attachments/assets/bd2e1b6a-9c4c-400d-8750-443f17387dad)
![Screenshot 2024-12-04 191841](https://github.com/user-attachments/assets/1ee75be5-9eb0-497c-919e-bcbd74759ac8)

**Comment by pellcorp** [comment]
Ok I updated the faq
