### ISSUE TITLE
Add a message on console for Filament Runout

### ISSUE THREAD

**Issue by leloupgris09** [pellcorp/creality#354]
When a filament runout occurs, nothing indicates that except for the tool head parked and the print pause.
The idea would be to have a message in the console:
"Filament Runout detected. Please reload and resume the print".

**Comment by pellcorp** [comment]
So we could reuse the `_CLIENT_VARIABLE` `variable_user_pause_macro` but that would trigger for a normal PAUSE as well, so it seems like we need to add a variable to `runout_gcode` in the `[filament_switch_sensor filament_sensor]` section in printer.cfg.

Something like this maybe:
https://github.com/pellcorp/creality/pull/358

**Comment by pellcorp** [comment]
This has been released.
