### ISSUE TITLE
Request: Integrate Anycubic Ace Pro MMU to creality

### ISSUE THREAD

**Issue by ducati1198** [pellcorp/creality#431]
I got a ace pro from Anycubic end delivery reverse engineered bin is public in github. Does anyone know if this possible to make work with K1 series. Four the cutter, we can use something similar to 3d chameleon open source cutter. The ace pro need a usb connection to the printer. It wil be amazing because you can get the ace pro for cheap

link to the reverse engineered files:

https://github.com/utkabobr/DuckACE

**Comment by pellcorp** [comment]
So this is not something I would be interested in adding to simple AF myself.   But you should join the discord and ask about it in a mod post

https://discord.gg/fhE9QTxuRv
