### ISSUE TITLE
Request: Integrate Anycubic Ace Pro MMU to creality

### ISSUE THREAD

**Issue by ducati1198** [pellcorp/creality#433]
got a ace pro from Anycubic end as the reverse engineered bin is public in github. Does anyone know if this possible to make work with K1 series. Four the cutter, we can use something similar to 3d chameleon open source cutter. The ace pro need a usb connection to the printer. It wil be amazing because you can get the ace pro for cheap

link to the reverse engineered files:

https://github.com/utkabobr/DuckACE

**Comment by pellcorp** [comment]
I already responded to another issue you opened

**Comment by ducati1198** [comment]
Im very sorry for that didn’t do by my purpose to repostOn Dec 26, 2024, at 17:07, Jason Pell ***@***.***> wrote:﻿
I already responded to another issue you opened
