### ISSUE TITLE
Cannot save bltouch offset in fluid

### ISSUE THREAD

**Issue by kerry-davis** [pellcorp/creality#82]
Steps to reproduce:

- baby step z offset via fluid
- click save and apply
- error is displayed

Reason:

[bltouch] section needs to be in printer.cfg and not in a seperate file

please see: https://klipper.discourse.group/t/save-config-section-bltouch-option-z-offset-conflicts-with-included-value/6640

To test this, in printer.cfg I manually copied the contents of bltouch.cfg and commented out the [include bltouch.cfg] saved and restarted. Saving the Z offset now works.

**Comment by pellcorp** [comment]
https://github.com/pellcorp/creality/pull/84
